import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>sumAI</title>
        <meta name="description" content="Generated by davinci-03" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">sumAI!</a>
        </h1>

        <p className={styles.description}>
          Your personal {' '}
          <code className={styles.code}>AI homework helper.</code>
        </p>

        <div className={styles.grid}>
          <a href="/demo" className={styles.card}>
            <h2>Demo &rarr;</h2>
            <p>Come ask us a question! School related or not, we got an answer.</p>
          </a>

          <a href="/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about how sumAI works!</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover the ways you can use sumAI to save time and be a more effective student.</p>
          </a>

          <a
            href=""
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Sign up &rarr;</h2>
            <p>
              Make us a part of your study group for less than a meal a month.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://raidenr.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Click here to check out our other stuff!
          
        </a>
      </footer>
    </div>
  )
}
